name: build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essentials

      - name: build
        run: |
          mkdir -p build
          gcc main.c -o build/notes-cli src/*.c

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: notes-cli
          path: build/notes-cli
