name: build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MinGW (gcc for Windows)
        run: choco install mingw -y

      - name: Add MinGW to PATH
        run: echo "C:\tools\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Build
        run: |
          mkdir build
          gcc main.c -o build/notes-cli.exe

