name: manifest-update

on:
  workflow_run:
    workflows: ["build-and-release"]
    types:
      - completed

jobs:
  update_scoop_manifest:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: get release tag
        id: tag
        run: |
          tag=$(gh api repos/${{ github.repository }}/releases/latest --jq .tag_name)
          echo "tag=$tag" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: download release artifact
        run: |
          curl -L -o notes-cli \
          https://github.com/${{ github.repository }}/releases/download/${{ steps.tag.outputs.tag }}/notes-cli

      - name: calculate SHA256 hash
        id: hash
        run: |
          HASH=$(sha256sum notes-cli | awk '{print $1}')
          echo "hash=$HASH" >> $GITHUB_OUTPUT

      - name: update scoop manifest
        run: |
          TAG="${{ steps.tag.outputs.tag }}"
          VERSION="${TAG#v}"
          URL="https://github.com/${{ github.repository }}/releases/download/${{ steps.tag.outputs.tag }}/notes-cli.exe"
          jq --arg ver "$VERSION" \
             --arg url "$URL" \
             --arg hash "${{ steps.hash.outputs.hash }}" \
             '.version=$ver | .url=$url | .hash=$hash' \
             notes-cli.json > notes-cli.json.tmp
          mv notes-cli.json.tmp notes-cli.json

      - name: commit and push manifest
        run: |
          git config user.name "gass-git"
          git config user.email "g.szada@gmail.com"
          git add notes-cli.json
          git commit -m "chore: updates scoop manifest for version ${{steps.tag.outputs.tag}}"
          git push
  
